name: flutter_app_pads00
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  like_button: ^1.0.4


  cupertino_icons: ^0.1.3
  audioplayers: ^0.16.1
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audios/
    - assets/images/
    - assets/audios/piano/
    - assets/audios/xylophone/
    - assets/audios/drum/